name: build

on:
  push:
    branches: [ master ]
    paths:
      - "site/**"
      - ".github/workflows/build.yaml"
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::424851482428:role/ci_cd_role
          aws-region: us-east-1