name: build 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::424851482428:role/ci_cd_role"

      - name: Upload to S3
        run: aws s3 cp ./site s3://blog-hosting-cat-1/ --recursive
        
