name: build 

on:
  push:
    branches:
      - master
    paths:
      - 'site/**'
      - '.github/workflows/build.yaml'
    pull_request:
      - master
      
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::424851482428:role/ci_cd_role"
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp ./site s3://blog-hosting-cat-1/ --recursive
        
